version: "3"
services: 
  ali-fastapi:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/user/src/app:ro
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    #env_file:
     # - ./env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=postgres 
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=96dc91a4f1e6eb5c2dcf52f4703a5145ec437b2ea65033712ff2c86e91b269aa
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - postgres

  postgres: 
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db:

      