name: First Code Deployment

on: [push, pull_request]

jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo 
        uses: actions/checkout@v2
      - name: setting up python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x86'
      - name: updating pip
        run: python -m pip install --upgrade pip
      - name: installing requirements
        run: pip install -r requirements.txt