"""autogernerating every single thing we need

Revision ID: e78ea3683b63
Revises: 39d9c08fc8a8
Create Date: 2022-02-18 19:29:20.523776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78ea3683b63'
down_revision = '39d9c08fc8a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
